apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-kube
  labels:
    app: website-kube
spec:
  replicas: 4
  selector:
    matchLabels:
      app: website-kube
  template:
    metadata:
      labels:
        app: website-kube
    spec:
      containers:
        - name: website-kube
          image: ${{env.OCI_IMAGE_VERSION}}
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: ${{secret.OCI_REGISTRY_SECRET}}