name: Application Deploy on OCI Cluster

on:
  push:
    branches:
      - main
    paths:
      - application/**
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v1

      - name: 'Set up Docker Buildx'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: 'Check Kubeconfig file'
        run: echo "${{ secrets.KUBECONFIG }}"
          
      - name: 'Installation kubectl'
        run: |
          mkdir /tmp/.kube
          curl -L -O "https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl" -o kubectl
          chmod +x kubectl
          mv kubectl /usr/local/bin
          echo "${{ secrets.KUBECONFIG }}" > /tmp/.kube/config
          echo "KUBECONFIG=/tmp/.kube/config" >> $GITHUB_ENV

      - name: 'Check Kubeconfig copy'
        run: cat KUBECONFIG=/tmp/.kube/config
          
      - name: 'Currently running services'
        run: kubectl -n kube-ns get pods
        
      - name: Login to OCI images registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.OCI_REGISTRY_URL }}
          username: ${{ secrets.OCI_REGISTRY_USERNAME }}
          password: ${{ secrets.OCI_KEY_FILE }}
          
      - name: 'Available platforms'
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: 'Building'
        run: |
          docker build --push -t ${{ secrets.OCI_REGISTRY_URL }}/${{ secrets.OCI_OBJECT_STORAGE_NAMESPACE }}/axtfvxixy3a6/aiservers/website_kube:v3 appllication/.
      
      - name: 'Deploying to Kubernetes'
        run: |
          sed -i 's/<OCI_OBJECT_STORAGE_NAMESPACE>/${{ secrets.OCI_OBJECT_STORAGE_NAMESPACE }}/g' application/site-deploy.yaml
          kubectl -n kube-ns apply -f application/site-deploy.yaml
      
      - name: 'Restarting application'
        run: |
          kubectl -n kube-ns rollout restart deployment website-kube
