name: Application Deploy on OCI Cluster

on:
  push:
    branches:
      - main
    paths:
      - application/**
  workflow_dispatch:
  
env:
  OCI_REGISTRY_URL: ${{ secrets.OCI_REGISTRY_URL }}
  OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
  OCI_KEY_FILE: ${{ secrets.OCI_KEY_FILE }}
  OCI_CONFIG: ${{ secrets.OCI_CONFIG }}
  KUBECONFIG: ${{ secrets.KUBECONFIG }}

jobs:
  build:    
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Configuring QEMU as deployer'
        uses: docker/setup-qemu-action@v1

      - name: 'Seting up Docker to build image'
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          
      - name: 'Installation OCI CLI'
        run: |
          mkdir ~/.oci
          echo "$OCI_CONFIG" > ~/.oci/config
          echo "$OCI_KEY_FILE" > ~/.oci/oci_pass.pem
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          echo "/home/runner/bin" >> $GITHUB_PATH
          exec -l $SHELL
          oci setup repair-file-permissions --file /home/runner/.oci/config
          oci setup repair-file-permissions --file /home/runner/.oci/oci_pass.pem
          
      - name: 'Installation kubectl'
        run: |
          mkdir /tmp/.kube
          curl -L -O "https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl" -o kubectl
          chmod +x kubectl
          mv kubectl /usr/local/bin
          echo "$KUBECONFIG" > /tmp/.kube/config
          echo "KUBECONFIG=/tmp/.kube/config" >> $GITHUB_ENV
          
      - name: 'Listing running services'
        run: kubectl -n kube-ns get pods
        
      - name: Login to OCI images registry
        uses: docker/login-action@v1
          
      - name: 'Available platforms'
        run: echo ${{ steps.buildx.outputs.platforms }}
        
      - name: 'Building image'
        run: |
          docker build --push -t "$OCI_REGISTRY_URL"/"$OCI_OBJECT_STORAGE_NAMESPACE"/axtfvxixy3a6/aiservers/website_kube:v3 appllication/.
      
      - name: 'Deploying to Kubernetes'
        run: |
          sed -i 's/<OCI_OBJECT_STORAGE_NAMESPACE>/"$OCI_OBJECT_STORAGE_NAMESPACE"/g' application/site-deploy.yaml
          kubectl -n kube-ns apply -f application/site-deploy.yaml
      
      - name: 'Rolling out application'
        run: |
          kubectl -n kube-ns rollout restart deployment website-kube
